# messing with while loop
# generated by the help of chatgpt

while True:
    number = input("Enter a number: ")
    
    if number == "":
        print("You did not enter a number!")
    elif not number.isdigit():
        print("You entered a non-numeric value!")
    else:
        try:
            number = int(number)
            break
        except ValueError:
            print("Invalid input! Please enter a valid number.")

while number != -1:
    number = input("Enter a number: ")
    if number == "":
        print("You did not enter a number!")
        continue
    try:
        number = int(number)
    except ValueError:
        print("Invalid input! Please enter a valid number.")

print(f"Thank you! {-1} is what I was looking for")